# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'distChecker.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Distchecker(object):
    def setupUi(self, Distchecker):
        Distchecker.setObjectName("Distchecker")
        Distchecker.resize(735, 653)
        Distchecker.setMaximumSize(QtCore.QSize(16777215, 16777210))
        Distchecker.setSizeIncrement(QtCore.QSize(1, 0))
        Distchecker.setAutoFillBackground(False)
        self.mainContainer = QtWidgets.QWidget(Distchecker)
        self.mainContainer.setObjectName("mainContainer")
        self.gridLayout = QtWidgets.QGridLayout(self.mainContainer)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.mainContainer)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.groupBox_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.topSlider = QtWidgets.QSlider(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topSlider.sizePolicy().hasHeightForWidth())
        self.topSlider.setSizePolicy(sizePolicy)
        self.topSlider.setMinimum(1)
        self.topSlider.setMaximum(200)
        self.topSlider.setPageStep(1)
        self.topSlider.setProperty("value", 50)
        self.topSlider.setSliderPosition(50)
        self.topSlider.setOrientation(QtCore.Qt.Horizontal)
        self.topSlider.setInvertedAppearance(False)
        self.topSlider.setInvertedControls(False)
        self.topSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.topSlider.setObjectName("topSlider")
        self.verticalLayout_3.addWidget(self.topSlider)
        self.topCount = QtWidgets.QLabel(self.groupBox_2)
        self.topCount.setSizeIncrement(QtCore.QSize(3, 0))
        self.topCount.setObjectName("topCount")
        self.verticalLayout_3.addWidget(self.topCount)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bottomSlider = QtWidgets.QSlider(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bottomSlider.sizePolicy().hasHeightForWidth())
        self.bottomSlider.setSizePolicy(sizePolicy)
        self.bottomSlider.setMinimum(0)
        self.bottomSlider.setMaximum(180)
        self.bottomSlider.setPageStep(1)
        self.bottomSlider.setProperty("value", 90)
        self.bottomSlider.setOrientation(QtCore.Qt.Horizontal)
        self.bottomSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.bottomSlider.setObjectName("bottomSlider")
        self.verticalLayout_2.addWidget(self.bottomSlider)
        self.bottomCount = QtWidgets.QLabel(self.groupBox_3)
        self.bottomCount.setTextFormat(QtCore.Qt.AutoText)
        self.bottomCount.setObjectName("bottomCount")
        self.verticalLayout_2.addWidget(self.bottomCount)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.saveButton = QtWidgets.QPushButton(self.groupBox)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)
        self.gridLayout.addWidget(self.groupBox, 2, 0, 1, 3)
        self.mainPicture = QtWidgets.QLabel(self.mainContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainPicture.sizePolicy().hasHeightForWidth())
        self.mainPicture.setSizePolicy(sizePolicy)
        self.mainPicture.setFrameShape(QtWidgets.QFrame.Box)
        self.mainPicture.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainPicture.setLineWidth(3)
        self.mainPicture.setText("")
        self.mainPicture.setPixmap(QtGui.QPixmap("graphology/white.bmp"))
        self.mainPicture.setScaledContents(False)
        self.mainPicture.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.mainPicture.setObjectName("mainPicture")
        self.gridLayout.addWidget(self.mainPicture, 0, 0, 2, 2)
        self.analysis = QtWidgets.QLabel(self.mainContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analysis.sizePolicy().hasHeightForWidth())
        self.analysis.setSizePolicy(sizePolicy)
        self.analysis.setFrameShape(QtWidgets.QFrame.Box)
        self.analysis.setFrameShadow(QtWidgets.QFrame.Raised)
        self.analysis.setLineWidth(3)
        self.analysis.setText("")
        self.analysis.setWordWrap(True)
        self.analysis.setObjectName("analysis")
        self.gridLayout.addWidget(self.analysis, 1, 2, 1, 1)
        Distchecker.setCentralWidget(self.mainContainer)

        self.retranslateUi(Distchecker)
        QtCore.QMetaObject.connectSlotsByName(Distchecker)

    def retranslateUi(self, Distchecker):
        _translate = QtCore.QCoreApplication.translate
        Distchecker.setWindowTitle(_translate("Distchecker", "Distance Checker"))
        self.groupBox.setTitle(_translate("Distchecker", "Operations"))
        self.groupBox_2.setTitle(_translate("Distchecker", "Top Spacer"))
        self.topCount.setText(_translate("Distchecker", "50"))
        self.groupBox_3.setTitle(_translate("Distchecker", "Bottom Spacer"))
        self.bottomCount.setText(_translate("Distchecker", "90"))
        self.saveButton.setText(_translate("Distchecker", "Save"))

