# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from label import RubberbandEnhancedLabel

class Ui_Graphology(object):
    def setupUi(self, Graphology):
        Graphology.setObjectName("Graphology")
        Graphology.resize(1081, 632)
        self.mainContainer = QtWidgets.QWidget(Graphology)
        self.mainContainer.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mainContainer.setObjectName("mainContainer")
        self.gridLayout = QtWidgets.QGridLayout(self.mainContainer)
        self.gridLayout.setContentsMargins(12, 12, 12, 12)
        self.gridLayout.setHorizontalSpacing(40)
        self.gridLayout.setVerticalSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.mainContainer)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(225, 600))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 206, 551))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.perk1 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.perk1.setText("")
        self.perk1.setObjectName("perk1")
        self.verticalLayout_2.addWidget(self.perk1)
        self.perk2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.perk2.setText("")
        self.perk2.setObjectName("perk2")
        self.verticalLayout_2.addWidget(self.perk2)
        self.perk3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.perk3.setMaximumSize(QtCore.QSize(225, 400))
        self.perk3.setText("")
        self.perk3.setObjectName("perk3")
        self.verticalLayout_2.addWidget(self.perk3)
        self.perk4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.perk4.setText("")
        self.perk4.setObjectName("perk4")
        self.verticalLayout_2.addWidget(self.perk4)
        self.perk5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.perk5.setText("")
        self.perk5.setObjectName("perk5")
        self.verticalLayout_2.addWidget(self.perk5)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout.addWidget(self.scrollArea, 1, 5, 1, 1)
        self.mainPicture = RubberbandEnhancedLabel(self.mainContainer)
        self.mainPicture.setAutoFillBackground(True)
        self.mainPicture.setFrameShape(QtWidgets.QFrame.Box)
        self.mainPicture.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainPicture.setLineWidth(3)
        self.mainPicture.setText("")
        self.mainPicture.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.mainPicture.setObjectName("mainPicture")
        self.gridLayout.addWidget(self.mainPicture, 1, 0, 2, 3)
        self.btnLoadImage = QtWidgets.QPushButton(self.mainContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLoadImage.sizePolicy().hasHeightForWidth())
        self.btnLoadImage.setSizePolicy(sizePolicy)
        self.btnLoadImage.setFlat(False)
        self.btnLoadImage.setObjectName("btnLoadImage")
        self.gridLayout.addWidget(self.btnLoadImage, 0, 0, 1, 1)
        self.featureBox = QtWidgets.QGroupBox(self.mainContainer)
        self.featureBox.setObjectName("featureBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.featureBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.buttonSlant = QtWidgets.QPushButton(self.featureBox)
        self.buttonSlant.setObjectName("buttonSlant")
        self.verticalLayout.addWidget(self.buttonSlant)
        self.buttonZone = QtWidgets.QPushButton(self.featureBox)
        self.buttonZone.setObjectName("buttonZone")
        self.verticalLayout.addWidget(self.buttonZone)
        self.buttonT = QtWidgets.QPushButton(self.featureBox)
        self.buttonT.setObjectName("buttonT")
        self.verticalLayout.addWidget(self.buttonT)
        self.buttonDist = QtWidgets.QPushButton(self.featureBox)
        self.buttonDist.setObjectName("pushButton_6")
        self.verticalLayout.addWidget(self.buttonDist)
        self.gridLayout.addWidget(self.featureBox, 1, 4, 2, 1)
        Graphology.setCentralWidget(self.mainContainer)
        self.statusbar = QtWidgets.QStatusBar(Graphology)
        self.statusbar.setObjectName("statusbar")
        Graphology.setStatusBar(self.statusbar)

        self.retranslateUi(Graphology)
        QtCore.QMetaObject.connectSlotsByName(Graphology)

    def retranslateUi(self, Graphology):
        _translate = QtCore.QCoreApplication.translate
        Graphology.setWindowTitle(_translate("Graphology", "Graphology"))
        self.btnLoadImage.setText(_translate("Graphology", "Load Image"))
        self.featureBox.setTitle(_translate("Graphology", "Features"))
        self.buttonSlant.setText(_translate("Graphology", "Slant Checker"))
        self.buttonZone.setText(_translate("Graphology", "Zone Checker"))
        self.buttonT.setText(_translate("Graphology", "t Analyze"))
        self.buttonDist.setText(_translate("Graphology", "Distance "))

