# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zoneChecker.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Zonechecker(object):
    def setupUi(self, Zonechecker):
        Zonechecker.setObjectName("Zonechecker")
        Zonechecker.resize(1071, 856)
        Zonechecker.setMaximumSize(QtCore.QSize(16777215, 16777210))
        Zonechecker.setSizeIncrement(QtCore.QSize(1, 0))
        Zonechecker.setAutoFillBackground(False)
        self.mainContainer = QtWidgets.QWidget(Zonechecker)
        self.mainContainer.setObjectName("mainContainer")
        self.gridLayout = QtWidgets.QGridLayout(self.mainContainer)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.mainContainer)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.uztSlider = QtWidgets.QSlider(self.groupBox_5)
        self.uztSlider.setPageStep(1)
        self.uztSlider.setOrientation(QtCore.Qt.Horizontal)
        self.uztSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.uztSlider.setObjectName("uztSlider")
        self.verticalLayout_5.addWidget(self.uztSlider)
        self.uztCount = QtWidgets.QLabel(self.groupBox_5)
        self.uztCount.setObjectName("uztCount")
        self.verticalLayout_5.addWidget(self.uztCount)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.mztSlider = QtWidgets.QSlider(self.groupBox_4)
        self.mztSlider.setPageStep(1)
        self.mztSlider.setOrientation(QtCore.Qt.Horizontal)
        self.mztSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.mztSlider.setObjectName("mztSlider")
        self.verticalLayout_4.addWidget(self.mztSlider)
        self.mztCount = QtWidgets.QLabel(self.groupBox_4)
        self.mztCount.setObjectName("mztCount")
        self.verticalLayout_4.addWidget(self.mztCount)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.bztSlider = QtWidgets.QSlider(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bztSlider.sizePolicy().hasHeightForWidth())
        self.bztSlider.setSizePolicy(sizePolicy)
        self.bztSlider.setMinimum(1)
        self.bztSlider.setMaximum(99)
        self.bztSlider.setPageStep(1)
        self.bztSlider.setProperty("value", 50)
        self.bztSlider.setSliderPosition(50)
        self.bztSlider.setOrientation(QtCore.Qt.Horizontal)
        self.bztSlider.setInvertedAppearance(False)
        self.bztSlider.setInvertedControls(False)
        self.bztSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.bztSlider.setObjectName("bztSlider")
        self.verticalLayout_3.addWidget(self.bztSlider)
        self.bztCount = QtWidgets.QLabel(self.groupBox_2)
        self.bztCount.setSizeIncrement(QtCore.QSize(3, 0))
        self.bztCount.setObjectName("bztCount")
        self.verticalLayout_3.addWidget(self.bztCount)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bzbSlider = QtWidgets.QSlider(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bzbSlider.sizePolicy().hasHeightForWidth())
        self.bzbSlider.setSizePolicy(sizePolicy)
        self.bzbSlider.setMinimum(0)
        self.bzbSlider.setMaximum(90)
        self.bzbSlider.setPageStep(1)
        self.bzbSlider.setProperty("value", 90)
        self.bzbSlider.setOrientation(QtCore.Qt.Horizontal)
        self.bzbSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.bzbSlider.setObjectName("bzbSlider")
        self.verticalLayout_2.addWidget(self.bzbSlider)
        self.bzbCount = QtWidgets.QLabel(self.groupBox_3)
        self.bzbCount.setTextFormat(QtCore.Qt.AutoText)
        self.bzbCount.setObjectName("bzbCount")
        self.verticalLayout_2.addWidget(self.bzbCount)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.saveButton = QtWidgets.QPushButton(self.groupBox)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)
        self.gridLayout.addWidget(self.groupBox, 2, 0, 1, 3)
        self.mainPicture = QtWidgets.QLabel(self.mainContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainPicture.sizePolicy().hasHeightForWidth())
        self.mainPicture.setSizePolicy(sizePolicy)
        self.mainPicture.setFrameShape(QtWidgets.QFrame.Box)
        self.mainPicture.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainPicture.setLineWidth(3)
        self.mainPicture.setText("")
        self.mainPicture.setPixmap(QtGui.QPixmap("graphology/white.bmp"))
        self.mainPicture.setScaledContents(False)
        self.mainPicture.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.mainPicture.setObjectName("mainPicture")
        self.gridLayout.addWidget(self.mainPicture, 0, 0, 2, 2)
        self.analysis = QtWidgets.QLabel(self.mainContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analysis.sizePolicy().hasHeightForWidth())
        self.analysis.setSizePolicy(sizePolicy)
        self.analysis.setFrameShape(QtWidgets.QFrame.Box)
        self.analysis.setFrameShadow(QtWidgets.QFrame.Raised)
        self.analysis.setLineWidth(3)
        self.analysis.setText("")
        self.analysis.setWordWrap(True)
        self.analysis.setObjectName("analysis")
        self.gridLayout.addWidget(self.analysis, 1, 2, 1, 1)
        Zonechecker.setCentralWidget(self.mainContainer)

        self.retranslateUi(Zonechecker)
        QtCore.QMetaObject.connectSlotsByName(Zonechecker)

    def retranslateUi(self, Zonechecker):
        _translate = QtCore.QCoreApplication.translate
        Zonechecker.setWindowTitle(_translate("Zonechecker", "Zone checker"))
        self.groupBox.setTitle(_translate("Zonechecker", "Operations"))
        self.groupBox_5.setTitle(_translate("Zonechecker", "UpperZoneTop"))
        self.uztCount.setText(_translate("Zonechecker", "0"))
        self.groupBox_4.setTitle(_translate("Zonechecker", "MiddleZoneTop"))
        self.mztCount.setText(_translate("Zonechecker", "20"))
        self.groupBox_2.setTitle(_translate("Zonechecker", "BottomZoneTop"))
        self.bztCount.setText(_translate("Zonechecker", "40"))
        self.groupBox_3.setTitle(_translate("Zonechecker", "BottomZoneBottom"))
        self.bzbCount.setText(_translate("Zonechecker", "50"))
        self.saveButton.setText(_translate("Zonechecker", "Save"))

